version: "3.0"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  engine:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8080:8080"

    environment:
      APP_DSN: host=postgres user=postgres password=postgres dbname=postgres port=5432 sslmode=disable TimeZone=Europe/Moscow
      APP_HOSTNAME: localhost:8080
      APP_HTTPADDR: :8080
      APP_DEVELOPMENT: "true"
      APP_SHOWSQL: "false"